2018-09-13 21:44:51,789 ERROR: Exception on /index [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/routes.py", line 30, in index
    if posts.has_prev else None
AttributeError: 'Pagination' object has no attribute 'prev_nume'
2018-09-13 21:45:30,249 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:43]
2018-09-13 21:50:20,280 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:43]
2018-09-16 17:58:26,612 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:45]
2018-09-16 18:07:16,699 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:45]
2018-09-16 18:51:25,187 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:45]
2018-09-16 18:51:59,387 ERROR: Exception on /reset_password_request [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/routes.py", line 162, in reset_password_request
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
2018-09-16 18:52:41,599 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:45]
2018-09-16 18:52:55,009 ERROR: Exception on /reset_password_request [POST] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/routes.py", line 170, in reset_password_request
    return redirect(url_for(login))
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 305, in url_for
    if endpoint[:1] == '.':
TypeError: 'function' object is not subscriptable
2018-09-16 18:54:56,362 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:45]
2018-09-17 19:20:00,442 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:47]
