2018-09-17 19:20:07,176 ERROR: Exception on /favicon.ico [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/errors.py", line 9, in not_found_error
    return render_template('404.html'), 404
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/base.html", line 19, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/base.html", line 19, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'index'
2018-09-17 19:20:07,194 ERROR: Exception on /favicon.ico [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/errors.py", line 9, in not_found_error
    return render_template('404.html'), 404
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/base.html", line 19, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/templates/base.html", line 19, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'index'
