2018-09-23 08:24:01,532 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:52]
2018-09-23 08:24:17,781 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:52]
2018-09-26 18:13:39,745 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:74]
2018-09-29 20:42:40,353 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:77]
2018-09-29 20:43:01,964 ERROR: Exception on /search [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2018-09-29 20:45:16,717 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:77]
2018-09-29 20:45:25,656 ERROR: Exception on /search [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2018-09-29 20:47:06,979 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:77]
2018-09-29 20:49:35,320 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:77]
2018-09-29 20:49:43,049 ERROR: Exception on /search [GET] [in /home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/main/routes.py", line 146, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/jakub/Programowanie/Python/flask/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/jakub/Programowanie/Python/flask/microblog/app/search.py", line 27, in query_index
    'from': (page - 1) * per_page, 'size': per_page}
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jakub/Programowanie/Python/flask/microblog/venv/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 'no [query] registered for [multi-match]')
2018-09-29 20:51:19,763 INFO: Microblog startup [in /home/jakub/Programowanie/Python/flask/microblog/app/__init__.py:77]
